/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AfinadorRouteImport } from './routes/afinador'
import { Route as AfinadorManualRouteImport } from './routes/afinador-manual'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CifrasRouteImport } from './routes/cifras'
import { Route as MetronomoRouteImport } from './routes/metronomo'
import { Route as ReconhecerRouteImport } from './routes/reconhecer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDonoRouteImport } from './routes/_authenticated/dono'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedRecentesRouteImport } from './routes/_authenticated/recentes'
import { Route as ApiImgRouteImport } from './routes/api/img'
import { Route as CifrasIndexRouteImport } from './routes/cifras.index'
import { Route as CifrasIdRouteImport } from './routes/cifras.$id'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AfinadorRoute = AfinadorRouteImport.update({
  id: '/afinador',
  path: '/afinador',
  getParentRoute: () => rootRouteImport,
} as any)
const AfinadorManualRoute = AfinadorManualRouteImport.update({
  id: '/afinador-manual',
  path: '/afinador-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CifrasRoute = CifrasRouteImport.update({
  id: '/cifras',
  path: '/cifras',
  getParentRoute: () => rootRouteImport,
} as any)
const MetronomoRoute = MetronomoRouteImport.update({
  id: '/metronomo',
  path: '/metronomo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconhecerRoute = ReconhecerRouteImport.update({
  id: '/reconhecer',
  path: '/reconhecer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonoRoute = AuthenticatedDonoRouteImport.update({
  id: '/dono',
  path: '/dono',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecentesRoute = AuthenticatedRecentesRouteImport.update({
  id: '/recentes',
  path: '/recentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiImgRoute = ApiImgRouteImport.update({
  id: '/api/img',
  path: '/api/img',
  getParentRoute: () => rootRouteImport,
} as any)
const CifrasIndexRoute = CifrasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CifrasRoute,
} as any)
const CifrasIdRoute = CifrasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CifrasRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afinador': typeof AfinadorRoute
  '/afinador-manual': typeof AfinadorManualRoute
  '/auth': typeof AuthRoute
  '/cifras': typeof CifrasRouteWithChildren
  '/metronomo': typeof MetronomoRoute
  '/reconhecer': typeof ReconhecerRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dono': typeof AuthenticatedDonoRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/recentes': typeof AuthenticatedRecentesRoute
  '/api/img': typeof ApiImgRoute
  '/cifras/$id': typeof CifrasIdRoute
  '/cifras/': typeof CifrasIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afinador': typeof AfinadorRoute
  '/afinador-manual': typeof AfinadorManualRoute
  '/auth': typeof AuthRoute
  '/metronomo': typeof MetronomoRoute
  '/reconhecer': typeof ReconhecerRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dono': typeof AuthenticatedDonoRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/recentes': typeof AuthenticatedRecentesRoute
  '/api/img': typeof ApiImgRoute
  '/cifras/$id': typeof CifrasIdRoute
  '/cifras': typeof CifrasIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/afinador': typeof AfinadorRoute
  '/afinador-manual': typeof AfinadorManualRoute
  '/auth': typeof AuthRoute
  '/cifras': typeof CifrasRouteWithChildren
  '/metronomo': typeof MetronomoRoute
  '/reconhecer': typeof ReconhecerRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dono': typeof AuthenticatedDonoRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/recentes': typeof AuthenticatedRecentesRoute
  '/api/img': typeof ApiImgRoute
  '/cifras/$id': typeof CifrasIdRoute
  '/cifras/': typeof CifrasIndexRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afinador'
    | '/afinador-manual'
    | '/auth'
    | '/cifras'
    | '/metronomo'
    | '/reconhecer'
    | '/admin'
    | '/dono'
    | '/favoritos'
    | '/recentes'
    | '/api/img'
    | '/cifras/$id'
    | '/cifras/'
    | '/admin/$id'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afinador'
    | '/afinador-manual'
    | '/auth'
    | '/metronomo'
    | '/reconhecer'
    | '/admin'
    | '/dono'
    | '/favoritos'
    | '/recentes'
    | '/api/img'
    | '/cifras/$id'
    | '/cifras'
    | '/admin/$id'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/afinador'
    | '/afinador-manual'
    | '/auth'
    | '/cifras'
    | '/metronomo'
    | '/reconhecer'
    | '/_authenticated/admin'
    | '/_authenticated/dono'
    | '/_authenticated/favoritos'
    | '/_authenticated/recentes'
    | '/api/img'
    | '/cifras/$id'
    | '/cifras/'
    | '/_authenticated/admin/$id'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AfinadorRoute: typeof AfinadorRoute
  AfinadorManualRoute: typeof AfinadorManualRoute
  AuthRoute: typeof AuthRoute
  CifrasRoute: typeof CifrasRouteWithChildren
  MetronomoRoute: typeof MetronomoRoute
  ReconhecerRoute: typeof ReconhecerRoute
  ApiImgRoute: typeof ApiImgRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afinador': {
      id: '/afinador'
      path: '/afinador'
      fullPath: '/afinador'
      preLoaderRoute: typeof AfinadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afinador-manual': {
      id: '/afinador-manual'
      path: '/afinador-manual'
      fullPath: '/afinador-manual'
      preLoaderRoute: typeof AfinadorManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cifras': {
      id: '/cifras'
      path: '/cifras'
      fullPath: '/cifras'
      preLoaderRoute: typeof CifrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metronomo': {
      id: '/metronomo'
      path: '/metronomo'
      fullPath: '/metronomo'
      preLoaderRoute: typeof MetronomoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconhecer': {
      id: '/reconhecer'
      path: '/reconhecer'
      fullPath: '/reconhecer'
      preLoaderRoute: typeof ReconhecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dono': {
      id: '/_authenticated/dono'
      path: '/dono'
      fullPath: '/dono'
      preLoaderRoute: typeof AuthenticatedDonoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recentes': {
      id: '/_authenticated/recentes'
      path: '/recentes'
      fullPath: '/recentes'
      preLoaderRoute: typeof AuthenticatedRecentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/img': {
      id: '/api/img'
      path: '/api/img'
      fullPath: '/api/img'
      preLoaderRoute: typeof ApiImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cifras/': {
      id: '/cifras/'
      path: '/'
      fullPath: '/cifras/'
      preLoaderRoute: typeof CifrasIndexRouteImport
      parentRoute: typeof CifrasRoute
    }
    '/cifras/$id': {
      id: '/cifras/$id'
      path: '/$id'
      fullPath: '/cifras/$id'
      preLoaderRoute: typeof CifrasIdRouteImport
      parentRoute: typeof CifrasRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDonoRoute: typeof AuthenticatedDonoRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedRecentesRoute: typeof AuthenticatedRecentesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDonoRoute: AuthenticatedDonoRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedRecentesRoute: AuthenticatedRecentesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CifrasRouteChildren {
  CifrasIdRoute: typeof CifrasIdRoute
  CifrasIndexRoute: typeof CifrasIndexRoute
}

const CifrasRouteChildren: CifrasRouteChildren = {
  CifrasIdRoute: CifrasIdRoute,
  CifrasIndexRoute: CifrasIndexRoute,
}

const CifrasRouteWithChildren =
  CifrasRoute._addFileChildren(CifrasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AfinadorRoute: AfinadorRoute,
  AfinadorManualRoute: AfinadorManualRoute,
  AuthRoute: AuthRoute,
  CifrasRoute: CifrasRouteWithChildren,
  MetronomoRoute: MetronomoRoute,
  ReconhecerRoute: ReconhecerRoute,
  ApiImgRoute: ApiImgRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
